baseURL = "https://www.chirpstack.io/"
languageCode = "en-us"
relativeURLs = true
title = "ChirpStack, open-source LoRaWAN Network Server stack"
googleAnalytics = "UA-3512995-9"
pygmentsUseClasses = true
theme = "chirpstack-hugo-theme"

[[menu.main]]
    pre = "<i class='fas fa-hand-point-right'></i>"
    name = "Overview"
    identifier = "overview"
    url = "/overview/"
    weight = 1

[[menu.main]]
    pre = "<i class='fas fa-book-open'></i>"
    name = "Guides"
    identifier = "guides"
    url = "/guides/"
    weight = 2

[[menu.main]]
    pre = "<i class='fas fa-download'></i>"
    name = "Install"
    identifier = "install"
    url = "/install/"
    weight = 3

[[menu.main]]
    pre = "<i class='fab fa-github'></i>"
    name = "Community & support"
    identifier = "community"
    url = "/community/"
    weight = 4

[params]
component = "docs"
